version: '2'
services:
  tools:
    # 用于 Git，vim, Composer 等工具
    build:
      context: ./images/tools
      dockerfile: Dockerfile
    volumes_from:  
      - php
    # 容器分配一个伪tty终端  
    tty: true  
  web:
    # Nginx 1.13: https://hub.docker.com/_/nginx/
    image: nginx:1.13
    # 将主机的 8090 端口映射到容器的 80 端口
    ports:
      - "8090:80"
    # 依赖php服务  
    depends_on:
      - php  
    # 同 php 一起共享 ./app 目录 
    volumes_from:
      - php  
    # 创建一个数据卷，由 ./images/nginx/config => /etc/nginx/conf.d  
    volumes:
      - ./images/nginx/config:/etc/nginx/conf.d  
  php:
    # PHP 7.1-fpm: https://hub.docker.com/_/php/
    # image: php:7.1-fpm
    build:
      # 指出 Dockerfile 所在的文件目录和文件名
      context: ./images/php
      dockerfile: Dockerfile
    volumes:
      - ./app:/mnt/app
  db:
    # mariadb:10.3 https://hub.docker.com/_/mariadb/
    image: mariadb:10.3
    # 配置一些环境变量
    environment:
      MYSQL_ROOT_PASSWORD: "Bojan"
      MYSQL_DATABASE: "app"
      MYSQL_USER: "bojan"
      MYSQL_PASSWORD: "Bojan"
    # 当前容器根目录挂在容器目录
    volumes:
      - ./db:/var/lib/mysql